project_id = "fgdsewgvjaybxfulchtu"

[functions.upload-book]
verify_jwt = false

[functions.chat]

[functions.chat]
verify_jwt = false

[functions.manage-shelves]
verify_jwt = false

[functions.manage-books]
verify_jwt = false

[functions.manage-profile]
verify_jwt = false